# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$NEXT_PATCH_VERSION 🌈' # 下一个补丁版本号。例如，如果最后一个标签或版本是 v1.2.3 ，则该值将为 v1.2.4 。这是最常用的值。
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'kind/feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'hotfix'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'enhancement'
  - title: '📃 Documentation'
    label: 'documentation'
exclude-labels:
  - 'skip-changelog'
replacers:
  - search: '/FN-(\d{1,4})/g'
    replace: '[FN-$1](https://betconstruct.atlassian.net/browse/FN-$1)'
autolabeler:
  - label: 'bugfix'
    branch:
      - '/bugfix\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'release'
    branch:
      - '/release\/.+/'
  - label: 'experimental'
    branch:
      - '/experimental\/.+/'
  - label: 'skip-changelog'
    branch:
      - '/(main|develop|experimental).*/'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'release'
  patch:
    labels:
      - 'hotfix'
publish: true
latest: true
template: |
  ## Changes

  $CHANGES
change-template: '* $TITLE'
